name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Install Rust toolchain
    - name: Install Rust toolchain
      run: rustup toolchain install nightly

    # Lint with fmt using nightly toolchain
    - name: Lint with fmt
      run: cargo +nightly fmt --all --check

    # Run tests
    - name: Run tests
      run: cargo test --all
