name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --all
    - name: Run tests
      run: cargo test --all
    - name: Lint with fmt
      run: cargo fmt --all --check
  benchmark:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --all --release
      - name: Run benches
        run: cargo bench